wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    t:
      1:
      - 1
      4: 3.6.13
      5: 0.10.31
      8:
      - 5
batch_size:
  desc: null
  value: 8
f0:
  desc: null
  value: f
f1:
  desc: null
  value: f
f10:
  desc: null
  value: f
f11:
  desc: null
  value: f
f12:
  desc: null
  value: f
f13:
  desc: null
  value: f
f14:
  desc: null
  value: f
f15:
  desc: null
  value: f
f16:
  desc: null
  value: f
f17:
  desc: null
  value: f
f18:
  desc: null
  value: f
f19:
  desc: null
  value: f
f2:
  desc: null
  value: f
f20:
  desc: null
  value: f
f21:
  desc: null
  value: f
f22:
  desc: null
  value: f
f23:
  desc: null
  value: f
f24:
  desc: null
  value: f
f25:
  desc: null
  value: f
f26:
  desc: null
  value: f
f27:
  desc: null
  value: f
f28:
  desc: null
  value: f
f29:
  desc: null
  value: f
f3:
  desc: null
  value: f
f30:
  desc: null
  value: f
f31:
  desc: null
  value: f
f32:
  desc: null
  value: f
f33:
  desc: null
  value: f
f34:
  desc: null
  value: f
f4:
  desc: null
  value: f
f5:
  desc: null
  value: f
f6:
  desc: null
  value: f
f7:
  desc: null
  value: f
f8:
  desc: null
  value: f
f9:
  desc: null
  value: f
iterations:
  desc: null
  value: 120000
lr:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 0.0005
